sudo: required
services:
  - docker

before_install:
  - docker build -t imgname -f Dockerfile.dev .

script:
  - docker run imgname npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-1-518476503157"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $ACCESS_KEY
  secret_access_key:
    secure: $SECRET_KEY